version: '3.0'

networks:
  app-network:
    driver: bridge

services:


  postgres:
    container_name: postgres
    image: m208s/nodejs2022q4-db
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRESS_PORT}:${POSTGRESS_PORT}
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  main:
    container_name: main
    image: m208s/nodejs2022q4-app
    build:
      context: ./
      dockerfile: ./docker/main/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-network
    depends_on:
      - postgres


volumes:
  pgdata:

